### ISSUE TITLE
Expand Contributing.md to invite contributions

### ISSUE THREAD

**Issue by gassmoeller** [OPM/pyopmspe11#83]
The current [contributing.md](https://github.com/OPM/pyopmspe11/blob/main/CONTRIBUTING.md) is a bit short. It sets some guidelines for contributions and discusses the process for users already familiar with contributing to github projects, but little else. For a small project like this a 10 page Contributing.md is maybe too much, but a bit of additional information would be good. E.g. the sentence `This project welcomes and values your contributions.` means a lot for potential contributors. Since most of this test is templateable there are good examples out there, e.g. maybe you can take over some of the text from https://contributing.md/example/.

Related to https://github.com/openjournals/joss-reviews/issues/7357.

**Comment by gassmoeller** [comment]
Oh I just found the following in README.md: `Contributions are more than welcome using the fork and pull request approach.`  which is a good start, but should be repeated in the Contributing.md. Still the text of Contributing.md should be extended.

Just to clarify, the JOSS criteria for contributing statements are: Are there clear guidelines for third parties wishing to 1. Contribute to the software 2. Report issues or problems with the software 3. Seek support

**Comment by daavid00** [comment]
Thanks @gassmoeller for your comment.

Now the [CONTRIBUTING.md](https://github.com/OPM/pyopmspe11/blob/main/CONTRIBUTING.md) includes (after the PR https://github.com/OPM/pyopmspe11/pull/97) information about:

> - Contribute to the software
> - Report issues or problems with the software
> - Seek support
> 
> In addition, in the section for Contribute to the software, information of how to run the tests locally is added.

A new Section in the documentation has been also created for the Contributing guidelines (after the PR  https://github.com/OPM/pyopmspe11/pull/99):

https://opm.github.io/pyopmspe11/contributing.html
